version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - cache:/app/.cache
      - public:/app/public
      - yarn_cache:/usr/local/share/.cache/yarn/v4
    ports:
      - '25700:25700'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      PORT: '25700'
    command: "yarn develop --host 0.0.0.0 --port 25700"

volumes:
  node_modules:
  cache:
  public:
  yarn_cache:
